#spring:
#  main:
#    allow-bean-definition-overriding: true
#  datasource:
#    url: jdbc:h2:mem:demo1;DB_CLOSE_DELAY=-1;
#    username: postgres2
#    password: Bounty33
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      use-new-id-generator-mappings: false
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        show-sql: true
#        format_sql: true


spring:
  datasource:
    url: jdbc:tc:postgresql:10.13://hostname/databasename
    username: postgres2
    password: Bounty33
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    hikari:
      driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa.properties.hibernate:
    show-sql: true
    format_sql: true
    jdbc.lob.non_contextual_creation: true